name: dokkanwebscraper build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    FUNCTION_NAME: 'dokkan-web-scraper'
    AZURE_FUNCTION_PACKAGE_PATH: '.'
    NODE_VERSION: 16.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Code Checkout'
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    - name: Deploy to Function
      id: deploy-to-function
      uses: azure/functions-deploy@v1
      with:
        app-name: ${{ env.FUNCTION_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
        package: ${{ secrets.AZURE_FUNCTION_PACKAGE_PATH }}