name: Publish Dokkan Web Scraper package to NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-test-build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: npm install, test, build
        run: |
          npm install
          npm test
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
