name: dokkanwebscraper build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
    FUNCTION_NAME: 'dokkan-web-scraper'
    AZURE_FUNCTION_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Code Checkout
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: 'NPM Install, Build, Test'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with: 
        name: scraper-node-app
        path: .

  # deploy:
  #   permissions: 
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment: 
  #     name: prod
  #     url: ${{ steps.deploy-to-function.outputs.function-url }}
    
  #   steps:
  #   - name: Download artifact from build job
  #   uses: actions/download-artifact@v3
  #   with: 
  #     name: scraper-node-app

  #   - name: Deploy to Function
  #   id: deploy-to-function
  #   uses: azure/functions-deploy@v2
  #   with:
  #     app-name: ${{ env.FUNCTION_NAME }}
  #     publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
  #     package: ${{ secrets.AZURE_FUNCTION_PACKAGE_PATH }}